name: todomvc_liquid
description: TodoMVC example
dependencies:
  browser: any
  liquid:
    git: git://github.com/localvoid/liquid.git
  vdom:
    git: git://github.com/localvoid/vdom.git
  route_hierarchical: any